// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjbjb0SMqaCgf46CaP8Hqggk0HGOUC25U',
    appId: '1:788526389103:web:410323e9a6d717a91e7a9a',
    messagingSenderId: '788526389103',
    projectId: 'ccwdb1',
    authDomain: 'ccwdb1.firebaseapp.com',
    storageBucket: 'ccwdb1.appspot.com',
    measurementId: 'G-2WBZBBZB11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-2Nx9T_Emid9ar6dMH9Lj84c34garrs',
    appId: '1:788526389103:android:0752d1bf6920e8731e7a9a',
    messagingSenderId: '788526389103',
    projectId: 'ccwdb1',
    storageBucket: 'ccwdb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0XC7C8Cy6UkxuBcznalzyY353M3HCIY',
    appId: '1:788526389103:ios:45fb379cb88594fd1e7a9a',
    messagingSenderId: '788526389103',
    projectId: 'ccwdb1',
    storageBucket: 'ccwdb1.appspot.com',
    iosBundleId: 'com.ccwassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0XC7C8Cy6UkxuBcznalzyY353M3HCIY',
    appId: '1:788526389103:ios:45fb379cb88594fd1e7a9a',
    messagingSenderId: '788526389103',
    projectId: 'ccwdb1',
    storageBucket: 'ccwdb1.appspot.com',
    iosBundleId: 'com.ccwassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjbjb0SMqaCgf46CaP8Hqggk0HGOUC25U',
    appId: '1:788526389103:web:b6e0719de76b36541e7a9a',
    messagingSenderId: '788526389103',
    projectId: 'ccwdb1',
    authDomain: 'ccwdb1.firebaseapp.com',
    storageBucket: 'ccwdb1.appspot.com',
    measurementId: 'G-BD8WNWLMHD',
  );

}